services:
  - type: web
    name: coffee-shop-pos-api
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install --include=dev && npx prisma generate && npm run build && npx prisma db push
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
